services:
  frontend:
    build: ./src/front-end
    ports:
      - '5173:80'
    depends_on:
      - backend
    volumes:
      - ./src/front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        tag: "frontend"
        syslog-format: "rfc5424"
    labels:
      service.name: "frontend"
      service.type: "web"
      app.component: "ui"

  backend:
    build:
      context: ./src/back-end
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    restart: unless-stopped
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        tag: "backend"
        syslog-format: "rfc5424"
    labels:
      service.name: "backend"
      service.type: "api"
      app.component: "server"
    environment:
      - VAULT_ADDR=http://vault:8200         # ðŸ‘ˆ point backend to the Vault container
      - VAULT_TOKEN=root                     # ðŸ‘ˆ dev token (only in dev mode!)
    depends_on:
      - vault

  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_TOKEN=root          # ðŸ‘ˆ dev token for simplicity
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200 
    cap_add:
      - IPC_LOCK                             # prevent memory swap for secrets
    volumes:
      - ./vault-data:/vault/file             # optional: persistent data
    command: server -dev                     # ðŸ‘ˆ dev mode; remove for production


volumes:
  sqlite-data:

networks:
  ft_transcendence_net:
    external: true